@startuml

hide circle

skinparam linetype ortho

entity "Person" as person {
  *id : number <<generated>
}

entity "Program" as program {
  *id : number <<generated>>
}

entity "ProgramParticipant" as program_participant {
  *id : number <<generated>>
  --
  program_id : foreign_key
  participant_id : foreign_key (person)
}

entity "SignatureRequirement" as signature_requirement {
  *id : number <<generated>>
}

entity "ProgramSignatureRequirement" as program_signature_requirement {
  *id : number <<generated>>
  --
  program_id : foreign_key
  signature_requirement_id : foreign_key
}

entity "Signature" as signature {
  *id : number <<generated>>
  --
  signature_requirement_id : foreign_key
  participant_id : foreign_key (person)
}

program }o-- program_participant
program_participant }o-- person
signature_requirement }o-- program_signature_requirement
program }o-- program_signature_requirement
signature_requirement }o-- signature
person }o-- signature

@enduml
