@startuml
Title Downtime Deployment - Timing Diagram

concise "Code Version" as code
concise "Database Schema State" as state
scale 10 as 200 pixels

code is "V0"
state is "S0"

@code
10 is {hidden}
20 is "V1"
code@10 <-> @20 : downtime

@state

10 is "S0 -> S1"
20 is "S1"

@enduml
