@startuml
Title Instantaneous Rollback - Timing Diagram
hide time-axis
concise "Code Version" as code
concise "Database Schema State" as db_state
scale 10 as 200 pixels

code is "V1"
db_state is "S1"

@code
15 is "V0"

@db_state
15 is "S1 -> S0"
20 is "S0"

@enduml
