@startuml
Title Instantaneous Deployment - Timing Diagram
hide time-axis
concise "Code Version" as code
concise "Database Schema State" as db_state
scale 10 as 200 pixels

code is "V0"
db_state is "S0"

@code
20 is "V1"

@db_state
20 is "S0 -> S1"
25 is "S1"

@enduml
